
FROM ubuntu:latest
MAINTAINER manclyon

############# First, Install JAVA ##########################
# Update the running system
RUN apt-get update -y

# Install the (probably) necessary packages
RUN apt-get install -y wget
RUN apt-get install -y tar

#Move into the /opt directory
WORKDIR /opt


# download java tar file into container
RUN  wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.tar.gz


# Extract file 
RUN tar zxvf jdk-8u112-linux-x64.tar.gz


#access the tmp/shared folder (where java.tar.gz lives) and copy across..
#ADD jdk-8u112-linux-x64.tar.gz /opt
#ADD apache-maven-3.2.5-bin.tar.gz /opt

#Install Java
RUN update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_112/bin/java 100
RUN update-alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_112/bin/javac 100

#'################# Now, Install Mule ###############################

RUN wget https://repository.mulesoft.org/nexus/content/repositories/releases/org/mule/distributions/mule-standalone/3.5.0/mule-standalone-3.5.0.tar.gz
RUN cd /opt && tar xvzf ~/mule-standalone-3.5.0.tar.gz
RUN echo "4a94356f7401ac8be30a992a414ca9b9 /mule-standalone-3.5.0.tar.gz" | md5sum -c
RUN rm ~/mule-standalone-3.5.0.tar.gz
RUN ln -s /opt/mule-standalone-3.5.0 /opt/mule 

CMD [ "/opt/mule/bin/mule" ]