
FROM ubuntu:latest
MAINTAINER manclyon

############# First, Install JAVA ##########################
# Update the running system
RUN apt-get update -y

# Install the (probably) necessary packages
RUN apt-get install -y wget
RUN apt-get install -y tar

#Move into the /opt directory
WORKDIR /opt


# download java tar file into container
RUN  wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.tar.gz


# Extract file 
RUN tar zxvf jdk-8u112-linux-x64.tar.gz


#access the tmp/shared folder (where java.tar.gz lives) and copy across..
#ADD jdk-8u112-linux-x64.tar.gz /opt
#ADD apache-maven-3.2.5-bin.tar.gz /opt

#Install Java
RUN update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_112/bin/java 100
RUN update-alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_112/bin/javac 100

#'################# Now, Install Mule ###############################

# Define environment variables
ENV         RUNTIME_VERSION "3.8.3"

ENV			JAVA_HOME /usr/bin/java

WORKDIR /opt
RUN mkdir mule
RUN cd mule
RUN wget http://s3.amazonaws.com/70aaf9be67f9bf88e5e78adcd7d6aa34/mule-ee-distribution-standalone-3.7.1.tar.gz 
RUN tar -xvzf mule-ee-distribution-standalone-3.7.1.tar.gz
RUN ./mule-enterprise-standalone-3.7.1/bin/mule


# Define mount points
VOLUME      ["/opt/mule/logs", "/opt/mule/apps", "/opt/mule/domains"]

# Remote debugger, JMX port, MMC agent, agent, default HTTP port
EXPOSE      5005 1098 7777 9997 8081

CMD [ "/opt/mule/bin/mule" ]